# Generated by Django 5.0.6 on 2024-06-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
