# Generated by Django 5.0.6 on 2024-06-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_brand_slug_car_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
    ]
